version: '3.1'
services:
    franlara.cv:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${APP_WWWGROUP}'
        image: franlara-8.2/cv
        domainname: franciscolaracasalilla.local
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - franlaranet
        depends_on:
            - maria-db
    maria-db:
        image: 'mariadb:10.6.12'
        ports:
            - '${MARIA_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MARIA_DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${MARIA_DB_DATABASE}'
            MYSQL_USER: '${MARIA_DB_USERNAME}'
            MYSQL_PASSWORD: '${MARIA_DB_USER_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'franlara-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - franlaranet
        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping','-p${MARIA_DB_ROOT_PASSWORD}' ]
            retries: 3
            timeout: 5s
        restart: always
networks:
    franlaranet:
        driver: bridge
volumes:
    franlara-mariadb:
        driver: local
