version: '3.1'
services:
    franlara.cv:
        build:
            context: ./infrastructure/docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${APP_WWWGROUP}'
        image: franlara-8.3/cv
        domainname: franciscolaracasalilla.local
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${APP_PORT_SECURE:-443}:443'
        environment:
            WWWUSER: '${APP_WWWUSER}'
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html:cached'
        networks:
            - franlaranet
        depends_on:
            - maria-db
    maria-db:
        image: 'mariadb:10.6.12'
        ports:
            - '${MARIA_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${MARIA_DB_ROOT_PASSWORD}'
            MARIADB_ROOT_HOST: '%'
            MARIADB_DATABASE: '${MARIA_DB_DATABASE}'
            MARIADB_USER: '${MARIA_DB_USERNAME}'
            MARIADB_PASSWORD: '${MARIA_DB_USER_PASSWORD}'
        volumes:
            - 'franlara-mariadb:/var/lib/mysql'
        networks:
            - franlaranet
        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping','-p${MARIA_DB_ROOT_PASSWORD}' ]
            retries: 3
            timeout: 5s
        restart: always
    maildebug:
        image: mailhog/mailhog
        networks:
            - franlaranet
        ports:
          - ${MAILHOG_PORT}:1025
          - ${MAILHOG_HTTP_PORT_EXTERNAL}:8025
        restart: always
networks:
    franlaranet:
        driver: bridge
volumes:
    franlara-mariadb:
        driver: local
