#!/usr/bin/env bash

export XDEBUG_HOST=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -n 1)

if [ $# -gt 0 ]; then

    if [[ "$1" == "start" ]]; then
        docker compose up -d

    elif [[ "$1" == "stop" ]]; then
        docker compose down

    elif [[ "$1" == "rebuild" ]]; then
        docker compose up -d --build

    elif [[ "$1" == "npm" ]]; then
        shift 1
        docker compose exec franlara.cv npm "$@"

    elif [[ "$1" == "node" ]]; then
        shift 1
        docker compose exec franlara.cv node "$@"

    elif [[ "$1" == "compile" ]]; then
        shift 1
        docker compose exec franlara.cv npm run build

    elif [[ "$1" == "composer" ]]; then
        shift 1
        docker compose exec franlara.cv composer "$@"

    elif [[ "$1" == "artisan" ]]; then
        shift 1
        docker compose exec franlara.cv php artisan "$@"

    fi

else
    docker-compose ps
fi
