FROM serversideup/php:8.3-fpm-nginx-alpine

LABEL maintainer="Fran Lara"

COPY --chown=www-data ./config/nginx/certs/franciscolaracasalilla.crt /etc/ssl/private/franciscolaracasalilla.crt
COPY --chown=www-data ./config/nginx/certs/franciscolaracasalilla.key /etc/ssl/private/franciscolaracasalilla.key