name: Push Branch
run-name: ${{github.actor}} made a ${{github.event_name}} for the branch ${{github.ref_name}}

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
      
jobs:
  lower-repository:
    name: Lower Repository Name
    runs-on: ubuntu-latest
    steps:
      - name: Downcase repository value and create docker image
        run: |
          echo "REPO=Hola" >> "$GITHUB_ENV"
          echo "DOCKER_IMAGE=${{vars.REGISTRY}}/${{env.REPO}}:${{github.ref_name}}" >> "$GITHUB_ENV"
          echo "Image ${{env.DOCKER_IMAGE}}"
          echo "Repo ${{env.REPO}}"
  
  build-image:
    name: Docker Image Creation
    needs: lower-repository
    uses: ./.github/workflows/build-docker-image.yml
    with:
      tag: ${{github.ref_name}}

  install-libraries:
    name: Library Caching
    needs: build-image
    uses: ./.github/workflows/cache-libraries.yml
    with:
      image-tag: ${{github.ref_name}}

  check-security:
    name: Check Composer Security
    runs-on: ubuntu-latest
    needs: install-libraries
    container: $DOCKER_IMAGE

    steps:
      - name: Checkout to check library security
        uses: actions/checkout@v4

      - name: Get cached Composer libraries
        uses: actions/cache@v4
        with:
          key: cache-${{vars.PROJECT}}-composer-${{hashFiles('composer.lock')}}
          path: vendor

      - name: Check Composer library security
        run: composer audit

  check-quality:
    name: Check Quality
    runs-on: ubuntu-latest
    needs: install-libraries
    container: laravelsail/php83-composer
    continue-on-error: true

    steps:
      - name: Checkout to find changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Determine if app folder have changed
        id: folder-change
        run: |
          if git diff --name-only ${{github.event.before}} --diff-filter=ACMRTUXB then
            echo "folder-changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Get cached Composer libraries
        uses: actions/cache@v4
        if: ${{steps.folder-change.outputs.folder-changed == 'true'}}
        with:
          key: cache-${{vars.PROJECT}}-composer-${{hashFiles('composer.lock')}}
          path: vendor

      - name: Check code quality
        if: ${{steps.folder-change.outputs.folder-changed == 'true'}}
        run: php -dmemory_limit=-1 vendor/bin/phpstan analyze $(git diff --name-only ${{github.event.before}} --diff-filter=ACMRTUXB -- '*.php')

  install-environment:
    name: CI Test Environment Installation
    needs: install-libraries
    uses: ./.github/workflows/install-environment.yml
    with:
      branch: ${{github.ref_name}}

  test-unit:
    name: Unit Test Suite
    needs: install-environment
    uses: ./.github/workflows/test-suite.yml
    with:
      report-name: unit-tests
      suite-name: Unit
      branch: ${{github.ref_name}}
      image-tag: ${{github.ref_name}}

  test-feature:
    name: Feature Test Suite
    needs: install-environment
    uses: ./.github/workflows/test-suite.yml
    with:
      report-name: feature-tests
      suite-name: Feature
      branch: ${{github.ref_name}}
      image-tag: ${{github.ref_name}}